### ISSUE TITLE
Any help ? :)

### ISSUE THREAD

**Issue by aminembarki** [SkeltonThatcher/aws-terraform-rancher-single-node-ha-elb#3]
There are warnings and/or errors related to your configuration. Please
fix these before continuing.

Errors:

  * data.aws_route53_zone.selected: Provider doesn't support data source: aws_route53_zone

**I set domain like in route53**

**Comment by richbos** [comment]
Hi, we have re-tested this and have received no error ourselves. Could I ask which version of Terraform you are using? And check that as advised the domain you have specified already exists in Route 53?

**Comment by aminembarki** [comment]
$ terraform.exe --version
Terraform v0.7.13
Thank you i upgrade to Terraform v0.9.6 it works :+1:
