### ISSUE TITLE
[feature request] Rancher server HA

### ISSUE THREAD

**Issue by maestrofx** [SkeltonThatcher/aws-terraform-rancher-single-node-ha-elb#5]
Hi @richbos ,

I try to enable full active/active HA of this rancher server.

As I dig into the rancher server config `server.tf` , the rancher server node doesn't use `aws_instance` resource to fire up the node, right? It's via `resource "aws_launch_configuration" "rancher_srv" { ... }`
Because I want to get the `private_ip` atrrib of the rancher node(s) passed to `--advertise-address` to create full active/active HA.

I added  `resource "aws_instance" {...}` and passed the ip of the node to `--advertise-address`, but Terraform ended up fire up one new ec2 node that not part of the rancher server itself.

Any help explanation about this issue, kinda welcome!

Thank you.

**Comment by richbos** [comment]
Hi, the HA aspect as you can see is single node and relies on the ec2 scaling group and launch config, and yes, it does not appear possible to obtain the dynamically assigned IP of a scaled instance using Terraform outputs.
I guess you could refactor the plan to deploy static server instances (x2), which although if configured for active/active would then provide resilience, however not really HA (which the single node plan was designed to do).
Apologies but we would not be looking to investigate active/active HA for the Rancher server within the scope of this current project.

**Comment by maestrofx** [comment]
I had thought before, it would be out of scope of this project, though. :)

Yes, I'll refactor based on this codebase for adding some features such as active/active HA, decoupling other parts, adding bastion, etc.

Thank you, @richbos. Cheers!

**Comment by richbos** [comment]
Closing this issue.
